
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author diana
 */
public class VAutentificacion extends javax.swing.JFrame {

    private String IP;
    private Integer portNum;
    private ServerInterface h;

    /**
     * Creates new form VAutentificacion
     */
    public VAutentificacion(String IP, Integer portNum) throws NotBoundException, MalformedURLException, RemoteException {
        initComponents();
        jIP.setText("localhost");
        this.IP = IP;
        this.portNum = portNum;
        String registryURL;
        registryURL = "rmi://" + IP + ":" + portNum + "/callback";
        // find the remote object and cast it to an 
        //   interface object
        this.h = (ServerInterface) Naming.lookup(registryURL);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jUsuario = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        registro = new javax.swing.JButton();
        jClave = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jIP = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPuerto = new javax.swing.JTextPane();
        jAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 242, 255));

        jUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(jUsuario);

        jLabel7.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        jLabel7.setText("(*)NOMBRE DE USUARIO: ");

        jLabel8.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        jLabel8.setText("(*) CLAVE:");

        login.setBackground(new java.awt.Color(225, 222, 240));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-log-in-64.png"))); // NOI18N
        login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        registro.setBackground(new java.awt.Color(225, 222, 240));
        registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-añadir-usuario-masculino-60.png"))); // NOI18N
        registro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });

        jClave.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        jClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClaveActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jLabel9.setText("BIENVENIDO");

        jLabel10.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        jLabel10.setText("(*) IP:");

        jIP.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(jIP);

        jLabel11.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        jLabel11.setText("(*) PUERTO:");

        jPuerto.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        jScrollPane3.setViewportView(jPuerto);

        jAviso.setBackground(new java.awt.Color(255, 51, 51));
        jAviso.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        jAviso.setForeground(new java.awt.Color(255, 51, 51));
        jAviso.setText("(*) Campos obligatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel7))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(login)
                            .addGap(18, 18, 18)
                            .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2)
                                .addComponent(jClave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jAviso))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(jClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jAviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if (!jUsuario.getText().isEmpty() && !jClave.getText().isEmpty() && !jIP.getText().isEmpty() && !jPuerto.getText().isEmpty()) {
            String nombre = null;
            try {
                nombre = this.h.verificarUsuario(jUsuario.getText(), jClave.getText());
            } catch (RemoteException ex) {
                Logger.getLogger(VAutentificacion.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (nombre != null) {
                try {
                    System.out.println("Server said " + h.sayHello());
                    ClientInterface callbackObj
                            = new ClientImpl();
                    // register for callback
                    Usuario usuario = new Usuario(nombre, jIP.getText(), Integer.parseInt(jPuerto.getText()));

                    for (Usuario u : h.buscarAmigos(usuario).values()) {
                        System.out.println(u.getPuerto());
                        usuario.setAmigos(u);
                    }
                    h.registerForCallback(callbackObj, usuario);
                    System.out.println("Registered for callback.");
                    System.out.println("Lookup completed ");
                    h.unregisterForCallback(callbackObj);
                    System.out.println("Unregistered for callback.");

                    VChat chat;
                    chat = new VChat(this, usuario);
                    this.setVisible(false);
                    chat.setVisible(true);

                } catch (RemoteException ex) {
                    Logger.getLogger(VAutentificacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_loginActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        // TODO add your handling code here:
        if (!jUsuario.getText().isEmpty() && !jClave.getText().isEmpty() && !jIP.getText().isEmpty() && !jPuerto.getText().isEmpty()) {
            
            try {
                if(!this.h.usuarioYaExiste(jUsuario.getText())){
                this.h.registrarUsuario(jUsuario.getText(), jClave.getText());
            

           
                System.out.println("Server said " + h.sayHello());
                ClientInterface callbackObj
                        = new ClientImpl();
                // register for callback
                Usuario usuario = new Usuario(jUsuario.getText(), jIP.getText(), Integer.parseInt(jPuerto.getText()));

                h.registerForCallback(callbackObj, usuario);
                System.out.println("Registered for callback.");
                System.out.println("Lookup completed ");
                h.unregisterForCallback(callbackObj);
                System.out.println("Unregistered for callback.");

                VChat chat;
                chat = new VChat(this, usuario);
                this.setVisible(false);
                chat.setVisible(true);
                }else{
                    jAviso.setText("Usuario ya existe");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(VAutentificacion.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_registroActionPerformed

    private void jClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAviso;
    private javax.swing.JPasswordField jClave;
    private javax.swing.JTextPane jIP;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextPane jPuerto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jUsuario;
    private javax.swing.JButton login;
    private javax.swing.JButton registro;
    // End of variables declaration//GEN-END:variables
}
