
import java.rmi.RemoteException;
import java.util.HashMap;

import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author diana
 */
public class VChat extends javax.swing.JDialog {

    /**
     * Creates new form VChat
     */
    private String nombre;
    private String clave;
    private HashMap<String, Amigo> amigos;
    private VAutentificacion padre;
    private ServerInterface serv;
    private Amigo amigoChat;
    private VSolicitudes sol;

    

    public VChat(java.awt.Frame padre, ServerInterface serv, String nombre, String clave) {
        super(padre);
       
        initComponents();
        this.amigoChat = null;
        this.padre = (VAutentificacion) padre;
        this.serv = serv;
        this.nombre=nombre;
        this.clave=clave;
        this.amigos=new HashMap<>();
        saludoCliente.setText("¡Hola " + nombre.toUpperCase() + "!");
        enviar.setEnabled(false);
        jemoji1.setEnabled(false);
            jemoji2.setEnabled(false);
            jemoji3.setEnabled(false);
            jemoji4.setEnabled(false);
        

    }
    
    public final void haySolicitudes() throws RemoteException {
        this.jnotificacion.setText("!!!!!");
        if(this.sol!=null){
            this.sol.actualizarTablita();
        }
    }
    
    public final void noHaySolicitudes() {
        this.jnotificacion.setText("");
    }

    public void comprobarNotificaciones(String usuario) throws RemoteException {
        
        if (serv.solicitudesAmistad(usuario).isEmpty()) {
            this.noHaySolicitudes();
        }
        else {
            this.haySolicitudes();
        }
    }
    public void setAmigos(HashMap<String,Amigo> amigos) throws RemoteException {
        this.amigos = amigos;
        
        ModeloTablaUsuarios chats;
        chats = (ModeloTablaUsuarios) jTablaAmigos.getModel();

        for (String nombre : amigos.keySet()) {
            chats.anadirFila(nombre);

        }
        comprobarNotificaciones(nombre);
    }
    public void setClave(String clave) {
        this.clave = clave;
    }

    public String getClave() {
        return clave;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablaAmigos = new javax.swing.JTable();
        saludoCliente = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jMensajeEnviar = new javax.swing.JTextPane();
        solicitudes = new javax.swing.JButton();
        enviar = new javax.swing.JButton();
        jchatear = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jChat = new javax.swing.JTextArea();
        jemoji2 = new javax.swing.JButton();
        jemoji4 = new javax.swing.JButton();
        jemoji3 = new javax.swing.JButton();
        jnotificacion = new javax.swing.JLabel();
        jemoji1 = new javax.swing.JButton();
        jcambiarClave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(637, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(244, 249, 255));
        jPanel1.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 0));

        jScrollPane4.setBackground(new java.awt.Color(244, 249, 255));
        jScrollPane4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setForeground(new java.awt.Color(244, 249, 255));

        jTablaAmigos.setOpaque(true);
        jTablaAmigos.setBackground(new java.awt.Color(252, 246, 220));
        jTablaAmigos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTablaAmigos.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jTablaAmigos.setModel(new ModeloTablaUsuarios());
        jTablaAmigos.setGridColor(new java.awt.Color(244, 249, 255));
        jTablaAmigos.setSelectionBackground(new java.awt.Color(223, 212, 171));
        jTablaAmigos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTablaAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaAmigosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTablaAmigos);

        saludoCliente.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        saludoCliente.setText("¡Hola Usuario!");

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jLabel10.setText("CONECTADOS:");

        jPanel2.setBackground(new java.awt.Color(244, 242, 255));

        jMensajeEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMensajeEnviarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jMensajeEnviarKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jMensajeEnviar);

        solicitudes.setBackground(new java.awt.Color(252, 246, 220));
        solicitudes.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        solicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-invitación-30.png"))); // NOI18N
        solicitudes.setText("SOLICITUDES");
        solicitudes.setToolTipText("");
        solicitudes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudesActionPerformed(evt);
            }
        });

        enviar.setBackground(new java.awt.Color(244, 242, 255));
        enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-enviar-mensaje-48.png"))); // NOI18N
        enviar.setBorder(null);
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        jchatear.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jchatear.setText("CHAT:");

        jChat.setBackground(new java.awt.Color(252, 246, 220));
        jChat.setColumns(20);
        jChat.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jChat.setRows(5);
        jScrollPane1.setViewportView(jChat);

        jemoji2.setBackground(new java.awt.Color(244, 242, 255));
        jemoji2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-estoy-aquí-48.png"))); // NOI18N
        jemoji2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jemoji2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemoji2ActionPerformed(evt);
            }
        });

        jemoji4.setBackground(new java.awt.Color(244, 242, 255));
        jemoji4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-globos-de-fiesta-48.png"))); // NOI18N
        jemoji4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jemoji4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemoji4ActionPerformed(evt);
            }
        });

        jemoji3.setBackground(new java.awt.Color(244, 242, 255));
        jemoji3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-estrellas-fugaces-48.png"))); // NOI18N
        jemoji3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jemoji3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemoji3ActionPerformed(evt);
            }
        });

        jnotificacion.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jnotificacion.setForeground(new java.awt.Color(255, 0, 51));

        jemoji1.setBackground(new java.awt.Color(244, 242, 255));
        jemoji1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-me-gusta-48.png"))); // NOI18N
        jemoji1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jemoji1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemoji1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jchatear))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addGap(18, 18, 18)
                                .addComponent(enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jnotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jemoji1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jemoji2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jemoji3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jemoji4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jnotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jchatear)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jemoji4)
                    .addComponent(jemoji2)
                    .addComponent(jemoji3)
                    .addComponent(jemoji1))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enviar)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcambiarClave.setBackground(new java.awt.Color(244, 249, 255));
        jcambiarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-contraseña-50.png"))); // NOI18N
        jcambiarClave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jcambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcambiarClaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(saludoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jcambiarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saludoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcambiarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
        jChat.append(nombre + ":  " + jMensajeEnviar.getText() + "\n");
        try {
            amigoChat.getInterfaz().recibirMensaje(nombre + ":  " + jMensajeEnviar.getText() + "\n", nombre);
            amigoChat.setConversacion(nombre + ":  " + jMensajeEnviar.getText() + "\n");
        } catch (RemoteException ex) {
            Logger.getLogger(VChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enviarActionPerformed
    public void recibirMensaje(String mensaje, String nombreU) {
        amigos.get(nombreU).setConversacion(mensaje);

        this.mostrarMensaje(mensaje, nombreU);
    }

    public void mostrarMensaje(String mensaje, String nombreU) {
        if (amigoChat != null) {
            if (amigoChat.getNombre().equals(nombreU)) {
                jChat.append(mensaje);
            }
        }
    }

    private void solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudesActionPerformed
        // TODO add your handling code here:
        
        try {
            sol = new VSolicitudes(this, nombre, serv);
            sol.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(VChat.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_solicitudesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            this.serv.unregisterForCallback(nombre, this.clave);
            this.dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(VChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jTablaAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaAmigosMouseClicked
        // TODO add your handling code here:

        ModeloTablaUsuarios amigosUsuario;
        amigosUsuario = (ModeloTablaUsuarios) jTablaAmigos.getModel();
        this.amigoChat = amigos.get((String) amigosUsuario.getValueAt(jTablaAmigos.getSelectedRow(), 0));
        jchatear.setText("Chatea con " + amigoChat.getNombre().toUpperCase());
        jChat.setText("");
        this.mostrarMensaje(amigoChat.getConversacion(), amigoChat.getNombre());
        jemoji1.setEnabled(true);
            jemoji2.setEnabled(true);
            jemoji3.setEnabled(true);
            jemoji4.setEnabled(true);

    }//GEN-LAST:event_jTablaAmigosMouseClicked

    private void jMensajeEnviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMensajeEnviarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMensajeEnviarKeyPressed

    private void jMensajeEnviarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMensajeEnviarKeyReleased
        // TODO add your handling code here:
        if (jMensajeEnviar.getText().isEmpty() || this.amigoChat == null) {
            enviar.setEnabled(false);
        } else {
            enviar.setEnabled(true);
        }
    }//GEN-LAST:event_jMensajeEnviarKeyReleased

    private void jcambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcambiarClaveActionPerformed
       VClave1 clave1 = new VClave1(this.padre,true, nombre, serv,this);
       clave1.setVisible(true);
       
    }//GEN-LAST:event_jcambiarClaveActionPerformed

    private void jemoji2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemoji2ActionPerformed
        // TODO add your handling code here:

        jChat.append( nombre + ":  " + "👋" + "\n");

        try {
            amigoChat.getInterfaz().recibirMensaje(nombre + ":  " + "👋" + "\n", nombre);
            amigoChat.setConversacion( nombre + ":  " + "👋" + "\n");
        } catch (RemoteException ex) {
            Logger.getLogger(VChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jemoji2ActionPerformed

    private void jemoji3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemoji3ActionPerformed
        // TODO add your handling code here:

        jChat.append( nombre + ":  " + "✨" + "\n");

        try {
            amigoChat.getInterfaz().recibirMensaje( nombre + ":  " + "✨" + "\n",  nombre);
            amigoChat.setConversacion( nombre + ":  " + "✨" + "\n");
        } catch (RemoteException ex) {
            Logger.getLogger(VChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jemoji3ActionPerformed

    private void jemoji4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemoji4ActionPerformed
        // TODO add your handling code here:
        jChat.append( nombre + ":  " + "🎉" + "\n");

        try {
            amigoChat.getInterfaz().recibirMensaje( nombre + ":  " + "🎉" + "\n",  nombre);
            amigoChat.setConversacion( nombre + ":  " + "🎉" + "\n");
        } catch (RemoteException ex) {
            Logger.getLogger(VChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jemoji4ActionPerformed

    private void jemoji1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemoji1ActionPerformed
        // TODO add your handling code here:
         jChat.append( nombre + ":  " + "❤" + "\n");

        try {
            amigoChat.getInterfaz().recibirMensaje( nombre + ":  " + "❤" + "\n",  nombre);
            amigoChat.setConversacion( nombre + ":  " + "❤" + "\n");
        } catch (RemoteException ex) {
            Logger.getLogger(VChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jemoji1ActionPerformed

    public void actualizarNuevosChats(Amigo u) throws RemoteException {
        amigos.put(u.getNombre(), u);
        System.out.println(u.getNombre());
        ModeloTablaUsuarios chats;
        chats = (ModeloTablaUsuarios) jTablaAmigos.getModel();
        chats.anadirFila(u.getNombre());

    }

    public void borrarChats(String u) throws RemoteException {

        this.amigos.remove(u);
        ModeloTablaUsuarios chats;
        if(amigoChat.getNombre().equals(u)){
            amigoChat=null;
            enviar.setEnabled(false);
            jemoji1.setEnabled(false);
            jemoji2.setEnabled(false);
            jemoji3.setEnabled(false);
            jemoji4.setEnabled(false);
            jChat.append("DESCONECTADO");
        }
        chats = (ModeloTablaUsuarios) jTablaAmigos.getModel();
        chats.borrarTabla();
        
        chats.setFilas(this.amigos.keySet());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviar;
    private javax.swing.JTextArea jChat;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextPane jMensajeEnviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablaAmigos;
    private javax.swing.JButton jcambiarClave;
    private javax.swing.JLabel jchatear;
    private javax.swing.JButton jemoji1;
    private javax.swing.JButton jemoji2;
    private javax.swing.JButton jemoji3;
    private javax.swing.JButton jemoji4;
    private javax.swing.JLabel jnotificacion;
    private javax.swing.JLabel saludoCliente;
    private javax.swing.JButton solicitudes;
    // End of variables declaration//GEN-END:variables
}
